#!/usr/bin/env bash
# SPDX-License-Identifier: AGPL-3.0-or-later
#
# Install the G9XC node worker on one Linux node (PS5 running Linux, or a
# salvage board). Idempotent: run it again after a config change and it will
# converge rather than duplicate.
#
#   sudo ./bringup/install_node.sh --unit-id ps5-001 \
#       --core /opt/ram-coffers --config /etc/g9-node/deployment.json
#
# It does not apply to an Xbox in Dev Mode: there is no systemd in that sandbox.
set -euo pipefail

UNIT_ID=""
CORE="/opt/ram-coffers"
CONFIG="/etc/g9-node/deployment.json"
BACKEND=""
HOST="0.0.0.0"
START=1

usage() {
    sed -n '3,12p' "$0" | sed 's/^# \{0,1\}//'
    exit "${1:-0}"
}

while [ $# -gt 0 ]; do
    case "$1" in
        --unit-id) UNIT_ID="$2"; shift 2 ;;
        --core)    CORE="$2"; shift 2 ;;
        --config)  CONFIG="$2"; shift 2 ;;
        --backend) BACKEND="$2"; shift 2 ;;
        --host)    HOST="$2"; shift 2 ;;
        --no-start) START=0; shift ;;
        -h|--help) usage 0 ;;
        *) echo "unknown argument: $1" >&2; usage 2 ;;
    esac
done

die() { echo "install_node: $*" >&2; exit 1; }

[ -n "$UNIT_ID" ] || die "--unit-id is required; it must match the inventory"
[ "$(id -u)" -eq 0 ] || die "run as root (it writes to /etc/systemd/system)"
[ -d "$CORE/gen9-cluster/gen9_cluster" ] \
    || die "$CORE does not look like a ram-coffers checkout"
command -v python3 >/dev/null || die "python3 is required"
command -v systemctl >/dev/null \
    || die "no systemd here. On an Xbox Dev Mode console the worker is started \
by the console, not by this script; see bringup/XBOX_DEVMODE_NOTES.md"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# The config is per-fleet and generated by deploy/gen_fleet_config.py; refusing
# to install without it prevents a node that comes up holding nothing.
[ -f "$CONFIG" ] || die "no deployment config at $CONFIG (generate it with \
deploy/gen_fleet_config.py --plan)"

# The service runs with PrivateTmp=yes, so a config under /tmp exists for you
# and not for the worker. Catch it here rather than in a restart loop.
case "$CONFIG" in
    /tmp/*|/var/tmp/*)
        die "$CONFIG is under a private tmp; the service cannot see it. Put \
the deployment config in /etc/g9-node/" ;;
esac

python3 - "$CONFIG" "$UNIT_ID" <<'PY' || die "this unit has no section in the deployment config"
import json, sys
config = json.load(open(sys.argv[1]))
sys.exit(0 if sys.argv[2] in config.get("nodes", {}) else 1)
PY

echo "== dependencies"
# Checked the way the service will see it: root, no login shell, PYTHONPATH
# pointing at the core. A --user install under the operator's account does not
# count, and finding that out from `systemctl status` at 3 a.m. is worse.
env -i PYTHONPATH="$CORE/gen9-cluster" python3 -c 'import numpy' 2>/dev/null \
    || die "numpy is not importable by the service user; install it with the \
node's package manager (python3-numpy). A pip --user install in your own \
account will not be visible to systemd"

echo "== reporting what this node can actually do"
# Informational: never fails the install. A node with no GPU stack is still a
# useful coffer, it just runs on the CPU.
(cd "$CORE/gen9-cluster" && python3 -m gen9_cluster probe --iterations 1) \
    || echo "warning: probe failed; the node will still serve, on whatever \
backend it can reach" >&2

echo "== unit files"
install -m 0644 "$SCRIPT_DIR/g9-node@.service" /etc/systemd/system/
install -d -m 0755 /etc/g9-node

ENV_FILE="/etc/g9-node/${UNIT_ID}.env"
if [ -f "$ENV_FILE" ]; then
    echo "keeping existing $ENV_FILE"
else
    cat > "$ENV_FILE" <<EOF
G9_CLUSTER=$CORE/gen9-cluster
PYTHONPATH=$CORE/gen9-cluster
G9_CONFIG=$CONFIG
G9_HOST=$HOST
G9_PORT=0
EOF
    [ -n "$BACKEND" ] && echo "G9_BACKEND=$BACKEND" >> "$ENV_FILE"
    chmod 0644 "$ENV_FILE"
    echo "wrote $ENV_FILE"
fi

systemctl daemon-reload
if [ "$START" -eq 1 ]; then
    systemctl enable --now "g9-node@${UNIT_ID}"
    sleep 2
    systemctl --no-pager --lines=20 status "g9-node@${UNIT_ID}" || true
else
    systemctl enable "g9-node@${UNIT_ID}"
    echo "enabled but not started (--no-start)"
fi

cat <<EOF

$UNIT_ID installed.

Next, from the deployment host:
  python3 deploy/check_fleet.py --inventory <csv> --connect
  python3 -m gen9_cluster probe --backend <backend> \\
      --write-fleet <fleet.json> --unit-id $UNIT_ID

The measurement matters: an unmeasured node is planned around a guess, and on
this hardware the guess can be off by more than a third.
EOF
